# Generated by Django 4.2.3 on 2023-07-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiophile_store', '0002_cartitem_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Shipping',
            new_name='shipping',
        ),
    ]
